# --- Project: Chinese & Western Orchestral Taxonomy ---
train_labels:
  - pipa
  - erhu
  - sheng
  - dizi
  - xiao
  - piano
  - guqin
  - suona
  - guzheng
  - percussion


# - strings
# - woodwinds
# - brass
# - electronic
#  - voice

irmas:
  - cel
  - cla
  - flu
  - gac  
  - gel
  - org
  - sax
  - tru
  - vio
  - voi