# --- Project: Chinese & Western Orchestral Taxonomy ---
train_labels:
  - strings
  - brass
  - percussion
  - woodwind
  - sheng
  - dizi
  - timpani
  - erhu
  - pipa
  - suona
  - guzheng
  - piano
  - guqin
  - xiao
  - yangqin

irmas:
  - cel
  - cla
  - flu
  - gac  
  - gel
  - org
  - sax
  - tru
  - vio
  - voi

